import os
import json
import re
from groq import Groq

_client: Groq | None = None

_SYSTEM_PROMPT = """You are an expert AI content detector. Analyze the provided text and determine whether it was written by a human or generated by an AI language model.

Return ONLY a valid JSON object with exactly these three fields:
- "ai_probability": float between 0.0 and 1.0 (0.0 = definitely human, 1.0 = definitely AI-generated)
- "attribution": one of "ai", "human", or "uncertain"
- "reasoning": one sentence explaining the strongest signal you detected

No text outside the JSON object."""


def _client_instance() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def analyze(text: str) -> float:
    """
    Returns probability of AI authorship in [0.0, 1.0].
    0.0 = almost certainly human. 1.0 = almost certainly AI.
    Raises RuntimeError on API failure or malformed response.
    """
    response = _client_instance().chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.1,
        max_tokens=150,
    )

    raw = response.choices[0].message.content.strip()

    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        # Model occasionally wraps JSON in markdown fences — extract it
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not match:
            raise RuntimeError(f"Groq returned non-JSON: {raw[:120]}")
        result = json.loads(match.group())

    ai_probability = float(result["ai_probability"])
    if not (0.0 <= ai_probability <= 1.0):
        raise ValueError(f"ai_probability out of range: {ai_probability}")

    return round(ai_probability, 4)
